const en = {
  translation: {
    "description": "THE THIRD ANNUAL CONFERENCE ON COMMUNICATIONS FOR BUSINESSES",
    "description link": "",
    "topic list": "IVR with voice recognition and voice robots for call centers, call management, text-to-speech conversion and speech recognition, videoconferences, messaging",
    "submit report": "CALL FOR PAPERS",
    "stay partner": "BECOME A PARTNER",
    "buy ticket": "BUY TICKETS",
    "language": "RU",
    "about conference": "About",
    "contact": "Contacts",
    "date": "OCTOBER 11 | MOSCOW, LOFT VESNA",
    "play button description": "How it was in 2017",
    'play button description2': 'Live Stream',
    "page2 header": "MAIN TOPICS",
    "telephony": "IVR with voice recognition",
    "speak bots": "and voice robots",
    "videoconf": "Videoconferences",
    "screenshare": "and streaming",
    "chats": "Messaging",
    "message": "and cognitive assistants",
    "manage": "Call management and callback",
    "speach recog": "Text-to-speech conversion and speech recognition",
    "page2_footer": "HOW IT WAS IN 2017",
    "form_text1": "Leave your email and stay tuned!",
    "form_text2": "",
    "subscr": "SUBSCRIBE",
    "call us": "Have questions? You can call us",
    "mail us": "Or drop an email",
    "codex": "CODE OF CONDUCT",
    'speaker more about': 'About speaker',
    'about header smallText':'About',
    'speakers header smallText':'Speakers',
    'shedule header smallText':'Shedule',
    'map header smallText':'Map',
    "speakers header": "SPEAKERS",

    "speakers_1_name": "Alexey Aylarov",
    'speakers_1_company': 'CEO, Voximplant',
    "speakers_1_post": "Voximplant",
    "speakers_1_description": "Alexey is a co-founder and CEO of Voximplant. In 2008, he graduated from Bauman Moscow State Technical University majoring in Computer Systems and Networks (Department of Informatics and Control Systems). He became a co-founder and CEO of Zingaya in 2010 and Voximplant in 2013. Alexey knows all about telephony, audio and video conferencing, messaging, chatbots and how to use them to increase the company's revenue. His area of interests and expertise includes the future of technology, international IT market, and company management.",

    "speakers_2_name": "Alexander Gridin",
    "speakers_2_post": "Head of Call Center, Shinservice.ru",
    "speakers_2_description": "A lawyer by training, Alexander works as the Call Center Project Manager at Shinservice and has over 10 years of experience in the industry. He is fond of vintage cars.",

    "speakers_3_name": "Ivan Seleznev",
    "speakers_3_post": "Head of Digital Division, Aristos",
    "speakers_3_description": "Ivan knows all the business processes in e-commerce from his own experience. He participated in the launch of several major projects of monobrand online stores. Now Ivan runs a digital division at Aristos Group, which is engaged in technical support and promotion of the official online stores for Philips, LG, Bosch, Grohe, Olympus, Unilever, Nestle, and others. Ivan makes complex concepts clear, then makes them simple to understand, and finally, beauty comes from the simplicity.",

    "speakers_4_name": "Anatoly Simakov",
    "speakers_4_post": "Business Development, Voximplant",
    "speakers_4_description": "In less than 2 years after Anatoly started working at JivoSite as a customer service manager, he became the Head of the Regular Customer Department. In August 2017, he joined Voximplant as a business development specialist.",

    "speakers_5_name": "Vasily Sazhko",
    "speakers_5_post": "Product Director, Voximplant",
    "speakers_5_description": "Vasily is an experienced Product Manager, with key accomplishments in the high tech business areas. Vasily headed the Project Management Department at Begun, which was the first company to introduce context advertising based on the pay-for-results principle. He was responsible for the auto.ru portal development and managed a search product portfolio of the sputnik.ru platform.",

    "speakers_6_name": "Ksenia Tatarintseva",
    "speakers_6_post": "Marketer, JivoSite",
    "speakers_6_description": "Before switching to marketing, Ksenia worked in Customer Support at Jivo and, at the same time, she started to write blog articles about customer service and user interaction. Now, as a marketing specialist, she continues to write about Jivo, online sales, and efficient customer communications.",

    "speakers_7_name": "Ekaterina Antsiferova ",
    "speakers_7_post": "Head of Sales Department, SDEK",
    "speakers_7_description": "Immediately after graduation, Ekaterina started working in the insurance and banking sectors. Before CDEK, she worked as a Project Manager for Federal Retail Chains at VTB Insurance: she commenced launching a new product to the market from scratch, facilitated the sales in partner networks and participated in training the managers. Currently, that project is one of the most dynamic and profitable in the company's portfolio. Ekaterina joined CDEK at the end of 2017 as the Head of the Sales Department at the Moscow branch.",

    "speakers_8_name": "Mikhail Kamaev",
    "speakers_8_post": "Project Manager, Voximplant",
    "speakers_8_description": "Mikhail developed partnership relations between Rambler/Kassa and cinemas throughout Russia. He joined the Voximplant team as a project manager and participated in the development of Smartcalls.io.",

    'speakers_9_name':'Pavel Zamorev',
    'speakers_9_post':'Head of Department, MTT',
    'speakers_9_description':'Pavel is responsible for the development of МТТ products and collaboration with the partners.',

    'speakers_10_name':'Kristina Lystina',
    'speakers_10_post':'Development manager, Shiptor.ru',
    'speakers_10_description':'Kristina is a business development manager at Shiptor, a logistics platform for online stores. She is mostly engaged in projects for B2B partners, cross-border logistics, and projects on complex eCommerce solutions.',

    'speakers_11_name':'Alexandra Cherkas',
    'speakers_11_company': 'VK Evangelist',
    'speakers_11_post':'VK',
    'speakers_11_description':'VK Evangelist, VK being the largest social network in Russia, with more than 90 million users. She’s in charge of Retail, Fashion and Sport sections of VK team, as well as developing small and medium sized businesses within the platform.',

    'speakers_12_name':'Pavel Makukha',
    'speakers_12_company': 'Sales product manager, SkyEng',
    'speakers_12_post':'SkyEng',
    'speakers_12_description':'Pavel is an experienced product manager. Before joining SkyEng, he was an operations manager for Gett Delivery, and also managed projects in Dostavista and Dodo Pizza.',

    'speakers_13_name':'Ilya Kozlov',
    'speakers_13_company': 'Project Manager VAS B2B, Virgin Connect',
    'speakers_13_post':'Virgin Connect',
    'speakers_13_description':'Ilya worked in telecommunication companies for more than 20 years, his first place of work was the Russia-on-Line project. At Virgin Connect, he developing new and existing VAS products.',

    'speakers_14_name':'Simon Dudley',
    'speakers_14_company': 'Head of Product Strategy and Sales Enablement, Logitech',
    'speakers_14_post':'Logitech',
    'speakers_14_description':'Simon Dudley is Head of Product Strategy and Sales Enablement for Logitech’s Video Collaboration business. Dudley joined Logitech in August 2016. Prior to that, he operated Excession Events, where he consulted organizations on optimizing their use of video collaboration. Dudley also spent over 25 years working in sales, marketing, and product management at companies like Polycom and LifeSize, which has given him a holistic view of the collaboration market. Dudley is an expert in the design, implementation and use of visual collaboration tools. He is a sought-after speaker in the collaboration industry, a published author, and the recipient of two patents. A native of the United Kingdom, Dudley currently resides in Austin, Texas.',

    'speakers_15_name':'Fikri Firat',
    'speakers_15_company': 'Product Manager of Strategic Products, Voxbone',
    'speakers_15_post':'Voxbone',
    'speakers_15_description':'Fikri keeps Voxbone’s services on the cutting edge. As Product Manager he enhances Voxbone’s APIs and gives business communications a boost with capabilities including WebRTC and Speech Analytics.',

    'speakers_16_name':'Grigory Petrov',
    'speakers_16_company': 'DevRel, Voximplant',
    'speakers_16_post':'Voximplant',
    'speakers_16_description':'His career in software development started in the late 90s: first as a designer, then as a product development manager. He participated in developing such software products as Radmin and Advanced IP Scanner, promoted interactive television NPTV. He is now working as a technology evangelist of Voximplant — cloud platform for telephony and video conferencing. His main professional interests include arranging program development processes, development control, cross-platform development. He acts as a speaker at IT conferences and a mentor at hackathons.',

    'speakers_17_name':'Artem Zarubenko',
    'speakers_17_company': 'CEO, Voxbee',
    'speakers_17_post':'Voxbee',
    'speakers_17_description':'He gained a vast experience during 5 years of working for IBS Group intergrator both in line and leading positions. He then launched the first coupon websites in Russia - Biglion and BigBuzzy, organized from scratch sales departments in companies developing online booking offices - Cassby and LIFE PAY. He’s been working in B2B sales for more than 14 years. His objective in Voxbee company is to help the business manage sales and customer relations by means of CRM systems and modern communication technologies. He’s convinced that a sales manager must sell using emotions instead of performing routine tasks. Mundane tasks can be left to robots.',

    'speakers_18_name':'Nikita Nikitinskiy',
    'speakers_18_company': 'R&D Head, IRELA',
    'speakers_18_post':'IRELA',
    'speakers_18_description':'For more than 7 years he’s worked in the field of computational linguistics and NLP for such companies as ABBYY, InfoWatch and Naumen. He has a great science and technology portfolio, has participated in international conferences. Nikita is in charge of research and design of solutions in the area of Deep Learning and NLP.',

    'speakers_19_name':'Nikita Levashov',
    'speakers_19_company': 'СТО, Angry Developers LLC',
    'speakers_19_post':'Angry Developers LLC',
    'speakers_19_description':'Co-founder of Angry Developers, works at Lia product. Graduate of Moscow Institute of Physics and Technology. Expert of machine learning and big data work. He streamlines the business workflow with the help of technologies. ',

    'speakers_20_name':'Ivan Boytsov',
    'speakers_20_company': 'Head of Department, Mail.ru for business',
    'speakers_20_post':'Mail.ru for business',
    'speakers_20_description':'He’s been in the field of creating and promoting B2B services for over seven years. At the moment he is in charge of Mail.Ru Group products. He manages Platform “Mail.Ru for business” – a universal business solution for companies which encompasses domain mail, cloud for business, collaboration services (calendar, messenger, intranet), mailing and polling services. He’s responsible for both product and technical side of the services.',

    'speakers_21_name':'Mikhail Nosov',
    'speakers_21_company':'Platform Architect, Voximplant',
    'speakers_21_post':'Voximplant',
    'speakers_21_description':'As a child he wanted to become a cosmonaut, but went on to train as a programmer. After graduation he worked with an integrator company, which had been developing software for Mosenergosbyt. At Voximplant he got involved in backend of the eponymous platform and messaging. He’s interested in  machine learning and karting.',

    'speakers_22_name':'Andrey Kovalenko',
    'speakers_22_company':'СТО, Voximplant',
    'speakers_22_post':'Voximplant',
    'speakers_22_description':'Co-founder and CTO of Voximplant. In 2008 he graduated from Bauman Moscow State Technical University with a degree in Computer Systems, Complexes and Networks. He’s been working in communications market for 15 years. In 2010 he co-founded Zingaya company and became its СТО, in 2013 – CTO of Voximplant.',

    'speakers_23_name':'Zviad Kardava',
    'speakers_23_company':'Developer Relations, Google',
    'speakers_23_post':'Google',
    'speakers_23_description':'Zviad is a developer and research analyst of distributed systems, industrial IoT and high-performance software. He enjoys being at the forefront of modern technologies and following their practical and academic aspects. Zviad has master’s degree of Bauman Moscow State Technical University. He’s especially keen on modern technologies and possibilities of their development.',

    'speakers_24_name':'Anastasia Danilina',
    'speakers_24_company':'Head of B2B Department, Yandex',
    'speakers_24_post':'Yandex',
    'speakers_24_description':'Has been working with Yandex since 2011. She has overseen various international projects of business development department. In 2015 she joined the team in charge of Yandex SpeechKit technologies. Her current project is Yandex.Dialogs platform. ',

    'speakers_25_name':'Taras Svitashev',
    'speakers_25_company':'Head of Customer Service, GrowFood',
    'speakers_25_post':'GrowFood',
    'speakers_25_description':'Started his career in RIA Novosti. He had worked in Tinkoff Bank for 6 years before joining GrowFood team.',

    'speakers_26_name':'Sergey Poroshin',
    'speakers_26_company':'Development Director, Voximplant',
    'speakers_26_post':'Voximplant',
    'speakers_26_description':'Co-founder and Development Director of Voximplant. In 2008 he graduated from Bauman Moscow State Technical University with a degree in Computer Systems, Complexes and Networks (Informatics And Control Systems Department). Prior to foundation of Zingaya and Voximplant used to work in “Svetets” (which specialized in developing IP telephony, IP PBX and IP Contact Center systems). In late 2007 he co-founded company “Innovative Communication Systems”',

    'speakers_27_name':'Andrey Savitskiy',
    'speakers_27_company':'Head of City Contact Center, IT Department of Moscow',
    'speakers_27_post':'IT Department of Moscow',
    'speakers_27_description':'Graduated from Social and Economic Institute with a degree in corporate management, then for a long time worked in the field of telecommunication services. Since 2011 he has been working as Head of City Contact Center in IT Department of Moscow.',

    'speakers_28_name':'Alexandr Kuznetsov',
    'speakers_28_company':'Team Leader, TrueConf',
    'speakers_28_post':'TrueConf',
    'speakers_28_description':'Project supervisor of TrueConf. He’s a famous specialist in signal processing and real time communications. He’s responsible for developing WebRTC app products and HTML5 SDK library for videoconferencing. Aleksandr’s solutions made it possible for tens of thousands of companies that use TrueConf servers worldwide to launch their own corporate webinars with advanced UI.',

    'speakers_29_name':'Oleg Cherezov',
    'speakers_29_company':'CEO, Sensemaking Lab',
    'speakers_29_post':'Sensemaking Lab',
    'speakers_29_description':'Research engineer and entrepreneur. He graduated from Moscow Institute of Electronics and Mathematics (MIEM). He worked as an IT expert and consultant in IBM EE/Russia and “Aplana”. He is a co-founder and SEO of SensemakingLab. The company deals with research and devising solutions for call centers in USA and Russia powered by data analysis, NLP and AI.',

    'speakers_30_name':'Alexey Simonov',
    'speakers_30_company':'Distribution manager, Logitech',
    'speakers_30_post':'Logitech',
    'speakers_30_description':'He’s been working in Logitech for over 10 years, in charge of developing distributor and corporate businesses: he coordinated largest competitive tenders in Russia, including supply of web cameras for Russian president elections.',

    'speakers_31_name':'Egor Sivkov',
    'speakers_31_company':'Chief Analyst, Sberbank',
    'speakers_31_post':'Sberbank',
    'speakers_31_description':'Graduated from Moscow Institute of Physics and Technology. He worked 3 years in Sberbank/SBT, developing a life insurance system for VIP clients within the “Sberbank Life Insurance” program, and carried out projects involving creating a voice assistant and KB Sberbank call center agent assistant.',

    'speakers_32_name':'Kirill Danilov',
    'speakers_32_company':'СТО, MTS Innovation Center',
    'speakers_32_post':'MTS Innovation Center',
    'speakers_32_description':'Kirill supervises a group of product developers, experienced in creating mobile and web apps for various platforms. He’s fond of hackathon movement, open technologies and mobile devices. His professional experience is over 14 years. He was in involved in projects with more than 2 million daily active users. He used to be an evangelist of Samsung Tizen platform in Russia and CIS, as well as Samsung SDK for Android. He is an award winner of AngelHack, BattleHack hackathons. He is a speaker and expert of SECR, DevConf, MoscowJs, GDG, Apps4All, LiveMobileCongress, MDDay, HackDay conferences.',

    'speakers_33_name':'Alexey Trankov',
    'speakers_33_company':'Development Director, TKK.Marketing',
    'speakers_33_post':'TKK.Marketing',
    'speakers_33_description':'In 2003 he completed postgraduate studies in university of Perm with a degree in textology. He worked as a project supervisor in MTS, Yandex, Sputnik (Rostelecom). He worked as Digital Director in Ogilvy advertising agency, as Managing Director in Buongiorno Digital agency, as Chief Marketing Officer in XBT holding (Cyprus). Co-founder of TKK.Marketing agency.',

    'speakers_34_name':'Gulnara Gorishnyaya',
    'speakers_34_company':'Head of Selection and Evaluation of People, Burger King',
    'speakers_34_post':'Burger King',
    'speakers_34_description':'Has an experience of over 10 years of organizing recruiting, adaptation and assessment processes from square one in federal retail companies with total staff exceeding 10 000 employees. She was in charge of a regional HR department in “Magnit” retail chain, carried out recruitment programs for an official dealer of PJSC MTS. Since 2014 has been in charge of Recruitment and Personnel Assessment Department of Burger King Russia. In the company she’s responsible for such projects as recruiting automation, HR branding, staff adaptation, student internships for newcomers and hiring peop',

    'speakers_35_name':'Dmitry Simоnov',
    'speakers_35_company':'CTO, Drimsim',
    'speakers_35_post':'Drimsim',
    'speakers_35_description':'He’s been working in IT since 1996. Used to work in Masterhost, Rambler, Yandex, Mail.Ru.',

    'speakers_36_name':'Alexey Baranov',
    'speakers_36_company':'Head of Development Department, Voximplant',
    'speakers_36_post':'Voximplant',
    'speakers_36_description':'Head of Voximplant Development Department. He’s been in sales and partnership relations development for over 11 years. His main hobby is travelling.',

    'speakers_37_name':'Alexey Kuligin',
    'speakers_37_company':'СЕО, TKK.Marketing',
    'speakers_37_post':'TKK.Marketing',
    'speakers_37_description':'In 2004 completed postgraduate studies in Perm State Technical University with a degree in Automated Control Systems. CEO of Reactive Media, the large and oldest web agency of Perm Krai (founded in 2001) and co-founder of a new digital agency TKK.Marketing.',

    'speakers_38_name':'Alexey Trankov',
    'speakers_38_company':'Development Director, TKK.Marketing',
    'speakers_38_post':'TKK.Marketing',
    'speakers_38_description':'In 2003 he completed postgraduate studies in university of Perm with a degree in textology. He worked as a project supervisor in MTS, Yandex, Sputnik (Rostelecom). He worked as Digital Director in Ogilvy advertising agency, as Managing Director in Buongiorno Digital agency, as Chief Marketing Officer in XBT holding (Cyprus). Co-founder of TKK.Marketing agency.',

    'speakers_39_name':'Alexey Kondratenko',
    'speakers_39_company':'Co-Founder, SpeechAnalytics.ru',
    'speakers_39_post':'SpeechAnalytics.ru',
    'speakers_39_description':'Aleksey is a co-founder and CEO of Speech Analytics. The service helps businesses analyze phone conversations, detect problem dialogues and find business growing points. He’s an executive partner in SalesArt marketing agency. In 2018 he graduated from Bauman Moscow State Technical University with a degree in Wheeled Vehicles (Mechanical Engineering department).',

    "schedule room1": "Hall 1",
    "schedule room1 pre": "Registration, welcome coffee",
    "schedule room1 pre2": "Conference opening, welcome speech",
    "schedule room1 event1 descr": "<strong>Keynote 2018</strong> <br>Machine learning and AI in communications, video conference and streaming, Dialogflow and cognitive assistants — 2018 results and 2019 trends.",
    "schedule room1 event2 descr": "<strong>Dialogflow: transforming a business with voice user interfaces and NLU <br> With each day the new service by Google is getting more and more mentions. Many of us know that Dialogflow can create chat bots for different platforms/languages on various devices, but few people have an idea of a true potential of the service.</strong>",
    "schedule room1 event3 descr": "<strong>Enabling Rapid Business Expansion with Cloud Communications</strong> <br> How consumers communicate with businesses is changing at a pace we’ve never seen before. However, the fact that voice is still the most preferred means of such an interaction proves the most important aspect of this experience : trust. Establishing trust in consumers is challenging and oftentimes closely coupled with local presence. I will explore challenges how recent developments in cloud communications platforms fit in an enterprise and how it can be leveraged to drive business expansion with minimal investment without compromising quality.",
    "schedule room1 event4 descr": "<strong>Yandex.Dialogs platform: Alisa as a new business channel</strong> <br> Early in the year Yandex started beta testing of Yandex.Dialogues platform. Based on it, you can now create your own “skill” for voice assistant Alisa – a special program that can communicate with the user and, for example, find the right product for the customer from your catalogue.",
    "schedule room1 event5 descr": "<strong>Call automation for online stores powered by popular CRM systems: Bitrix24 case</strong> <br> “Automated calls are expensive and won’t help my business whatsoever”, that’s what a lot of small online shop owners think, but they are grossly mistaken. In my speech I’m going to examine out-of-the-box solutions as illustrated by intergration of Smartcalls service into Bitrix24 CRM.",
    "schedule room1 event6 descr": "<strong>Control of 100% of calls in the company</strong> <br> In the report, we will discuss how to control service scripts, look for business growth points using speech analytics, improve employee discipline, improve service quality and protect against information leaks.",
    "schedule room1 event7 descr": "<strong>Computerize it: how you can lower HR burden by half using a robot recruiter <br> In this report we’ll examine the ways of eliminating useless processes and optimizing the useful ones. We’ll explore in detail what aspects can be handled by robots and where a human is indispensable. We’ll analyze the figures of a robot recruiter economy.</strong>",
    "schedule room1 event8 descr": "<strong>SkyEng: the journey from Google Sheets to lead processing automation platform</strong> <br> What we’ve done and why we’ve done it, the lessons we’ve learnt. Spoiler: transition from Google Sheets, Zoiper and 5 calls an hour to an automation platform and minute-by-minute control over operator’s working hours.",
    "schedule room1 event9 descr": "<strong>GrowFood: cloud call center for a food delivery service</strong> <br> Trying to provide a convenient service for the customers, Grow Food came up with a cloud call center. Customer wait list for connecting to an agent, uploading customer data sheets from CRM while incoming calls, automated outbound customer calling with an offer to extend the plan validity: results, implementation peculiarities.",
    "schedule room1 event10 descr": "<strong>Enabling Rapid Business Expansion with Cloud Communications</strong> <br> How consumers communicate with businesses is changing at a pace we’ve never seen before. However, the fact that voice is still the most preferred means of such an interaction proves the most important aspect of this experience : trust. Establishing trust in consumers is challenging and oftentimes closely coupled with local presence. I will explore challenges how recent developments in cloud communications platforms fit in an enterprise and how it can be leveraged to drive business expansion with minimal investment without compromising quality.",
    "schedule room1 lunch": "Lunch",
    "schedule room1 event11 descr": "<strong>Video conferencing: why after 25 years of failures everything’s finally working</strong> <br> The video conferencing industry has been a failure for over 25 years, with only a pathetically small number of meeting spaces being suitably equipped. Come and listen to why Logitech and the Cloud solution providers have changed the game, and how we are finally at the start of mass deployed video communications.",
    "schedule room1 event12 descr": "<strong>Remote online training based on videoconferencing, Smart University case <br> Online learning has become an integral part of our lives, saving both time and money and erasing the boundaries between the teacher and the student: you can study any day of the week, with your teacher being in another city. Today we’ll speak about an ideal combination for creating an online university:  top teachers, an interactive workbook and one to one communication via video conferencing.</strong>",
    "schedule room1 event13 descr": "<strong>Business problem solving from a single entry point</strong> <br> What are SaaS marketplaces? Why are they better than specific services? What’s the difference between a good and bad marketplace? What’s the most effective way to solve any business problem, including organizing communication with the customer by means of business platforms?",
    "schedule room1 event14 descr": "<strong>Communications for business in social networks: chats, calls, video streaming <br> To do business today is to communicate: with suppliers, customers and partners. Interaction via Vkontakte means 5 billion messages daily, 1 billion likes and 97 million active users monthly, 77% of who visit the network with their mobile devices. Aleksandra’s going to tell you what opportunities Vkontakte’s new features offer to your business.</strong>",
    "schedule room1 event15 descr": "<strong>Business models of using voice technologies in conjunction with digital products</strong> <br> In the speech I’m going to dwell on the notion of a mono service and its potential; answer the question of why “bare” technologies don’t impress businesses. We’ll discuss complex services as a resource for completing any business task and find out how one can make a technology easily implementable.",
    "schedule room1 event16 descr": "<strong>Trigger robocalls from CRM</strong> <br> Robocalls in real life: collecting product reviews, outside expert performance monitoring, refilling information. How to advance a deal to the next level of amoCRM, when emails fail and employees are  scarce. ",
    "schedule room1 event17 descr": "<strong>Voice user interface for product and service payments <br> Voice user interfaces have long been a subject of discussion, but lack of practical solutions is still an urgent issue here. One of business needs is a simple way to pay for a product or service in compliance with necessary risk and safety requirements. Cashing a check after an order, paying debts, calculating and accepting a payment when the cost of regular services is variable – all of this is possible thanks to modern voice activation technologies and flexible billing. We’ll present to you cases of PayCall technology operation in business and in state services.</strong>",
    "schedule room1 litings": "Litings",
    "schedule room1 post": "Conference Closing",
    "schedule room1 post2": "Afterparty",

    "schedule room2": "Hall 2",
    "schedule room2 event1 descr": "<strong>How to provide fault tolerance of a cloud service <br> “How can you measure service availability and why is 100% uptime impossible? What can be reserved and how? How can you calculate SLA?” These and other questions will be discussed in a speech devoted to Voximplant platform as an example of providing fault tolerance for a cloud service.</strong>",
    "schedule room2 event2 descr": "<strong>Google Cloud Platform: application of machine learning in practice <br> Zviad is going to speak about tools in the field of machine learning and data analysis, answer the question of what projects will benefit from using off the shelf solutions rather than devising customized ones. He’ll touch upon Vision API, Speech API, WaveNet, Tensorflow technologies and after his speech he’s going to answer some technical questions.</strong>",
    "schedule room2 event3 descr": "<strong>Methods of performance optimization of WebRTC on mobile devices (mixer vs single streams)</strong> <br>Peculiarities of working with media streams when participating in a group WebRTC conference on a mobile device (traffic growth problem) How to eliminate the influence of a number of participants on the device performance (mixing of broadcasters on the server) Advantages and disadvantages of stream mixing on the server side Post processing of a mixed image to receive an individual layout on the side of the mobile device.",
    "schedule room2 event4 descr": "<strong>Dialogflow: teaching robots to keep up a conversation during a call</strong> <br> You must have seen in work the existing voice assistants: Alisa, Siri, Alexa. But how hard is it actually to create one’s own AI and teach the program to keep up a conversation by asking questions, checking back and understanding the reply? I’m going to speak about integration of Google’s new cognitive platform and programmable telephony by Voximplant. You’ll just upload a lot of text, lay out its meaning, add some JavaScript magic and here you are: our own Alisa is ready to answer calls!",
    "schedule room2 event5 descr": "<strong>NLP for creating dialogue scripts in text and phone bots </strong> <br> How does oral intelligence operate? What is the pattern of a goal-oriented bot? How can one work with limitations of NLP algorithms when dialogue programming? I’m going to speak about principles of operation of linguistic algorithms and their use in creating intelligent robots for business.",
    "schedule room2 event6 descr": "<strong>Neural networks in developing a voicemail detector</strong> <br> How often have you heard that the number is busy, but you can leave a voicemail message? And how often have you actually listened to these messages? Such voice mailboxes have become a serious issue in business. While outbound calling campaigns agents are often connected to voicemail, which leads to irrelevant call statistics and business losing its money. In my speech I’m going to focus on our experience of developing voicemail detection: the difficulties we’ve faced and how we’ve ended up with neural networks.",
    "schedule room2 event7 descr": "<strong>NLP, ML, self-service, digital transformation, knowledge base and a couple more clever terms that really work for intellectualization of the service support <br> Every day service support receives thousands of calls which are processed from scratch, forwarded to wrong specialists and long awaited solutions are not always right. “Does the service support take long to answer? How often are you not satisfied with an answer? Has a chat bot ever helped you?” – this speaker is going to reveal how you can simplify these processes by creating a digital transformation ecosystem within the project’s existing IT environment and using accumulated experience of the service support, NLP and Machine Learning. </strong>",
    "schedule room2 event8 descr": "<strong>What is under the bonnet of an international travel SIM card <br> I’ll speak about supporting a Multi IMSI SIM card: ancient philosopher Diogenes’ principles behind the architecture building, integration with MVNx-billing systems, with VoIP, SMS, and API beam for infrastructural binding of the entire project.</strong",
    "schedule room2 event9 descr": "<strong>The topic is yet to be confirmed</strong",

    'schedule header smallText':'Programm',
    "schedule header": "SCHEDULE",
    "schedule section1": "Section 1",
    "schedule section1 pre": "",
    'schedule section1 pre2':'INTERCOM E-COM EDITION OPENING',
    "schedule section1 descr": "QUALITY CONTROL PROCESSES AUTOMATION",
    "schedule section1 event1": "Section opening, moderator’s welcome speech",
    "schedule section1 event2": "<strong>Vasily Sazhko — Product Director, Voximplant</strong> Reducing costs in a falling market due to the automation of measuring the customer loyalty index (NPS). A workshop on creating robotic scenarios to collect customers' feedback based on the example of an online food delivery store.",
    "schedule section1 event3": "<strong>Otari Melikishvili — Head of QA projects</strong> According to statistics, one dissatisfied customer affects 6 other people, who would never shop in a store with a poor quality of service. At the same time, 10 satisfied customers will attract only 1 new visitor. In this talk, we will look at how modern technologies help to measure the NPS and CSI and identify gaps in the provided service in a timely manner.",
    "schedule section1 event4": "<strong>Pavel Zamorev — Head of Department</strong> Every business owner faces the need to control employees at some point. With modern technologies, you don't have to be in the office all the time to know how each employee works. The MTT SIM card allows you to receive call statistics and listen to records of your managers' conversations on mobile phones even without access to the Internet.",

    "schedule section2": "Section 2",
    "schedule section2 pre": "LUNCH BREAK",
    "schedule section2 descr": "ORDERING PROCESSES AUTOMATION",
    "schedule section2 event1": "Section opening, moderator’s welcome speech",
    "schedule section2 event2": "<strong>Ivan Seleznev — Head of Digital Division, Aristos Group</strong> Since 2010, Aristos has been engaged in a full-service outsourcing of online sales for the large brand companies: Philips, LG, Grohe, Rehau, Castrol, Olympus, Unilever, etc. In 2017, Aristos launched its own telephony solution because none of the available solutions could fully meet the company's needs. The new solution provided the online store operators with a user-friendly interface for customer service and allowed them to get all the customer details by phone number as well as quickly furnish the required information on orders.",
    "schedule section2 event3": "<strong>Alexey Aylarov — CEO, Voximplant</strong> Telephony integration with Google Dialogflow to accept orders automatically: a case study of a large pizza restaurant in Moscow. Spoiler alert: it is stuffed with AI, ML, and intelligent IVR.",
    "schedule section2 event4": "<strong>Ksenia Tatarintseva — Marketer, JivoChat</strong> Most of the customers prefer to call rather than send a written request. It is especially true for those who search for goods and services from a mobile phone and for the elderly people who are unaccustomed to expressing their thoughts in writing. In January 2018, Jivosite launched a callback request service for mobile devices, which shortened the customer's path to purchase and turns a website from an entry point into a sales point.",
    "schedule section2 event5": "<strong>Anatoly Simakov — Business Development, Voximplant</strong> & <strong>Alexander Gridin — Head of Call Center, Shinservice.ru</strong> An interactive voice response system for customers based on a case study of Shinservice, a leading online store that handles over 4,500 similar calls per day during high season. Spoiler alerts: the system saves time and money and reduces the load on operators; instantly identifies customers by phone numbers and fetches the up-to-date order status (customers can provide the order number using voice or buttons); notifies customers about the order dispatch; automatically confirms the appointments and reminds the customers about the scheduled maintenance.",

    "schedule section3": "Section 3",
    "schedule section3 pre": "LUNCH BREAK",
    "schedule section3 descr": "DELIVERY PROCESSES AUTOMATION",
    "schedule section3 event1": "Section opening, moderator’s welcome speech",
    "schedule section3 event2": "<strong>Ekaterina Antsiferova — Head of sales department, SDEK</strong> A smart call warns the customers of CDEK that a courier is going to deliver a package in an hour or that they are late — all using the IVR technology. In response to a call, a customer can acknowledge that he or she is ready to accept the package, ask to change the delivery date and time or to contact the courier. The courier starts a call in a mobile app, which also shows the customer's response: this is convenient and efficient both for the couriers and the customers. CDEK is a leading express delivery company in Russia with more than 1000 divisions and representative offices in Russia and abroad.",
    "schedule section3 event3": "<strong>Mikhail Kamaev — Project Manager, Voximplant</strong>An automated notification system that reminds the customers of the expiry date of the goods stored at a pick-up point and suggests canceling the order or extending the storage period. The case is based on the example of an international casual clothing brand that has been steadily holding the leading positions in the Russian clothing market for the past few years and ranks among TOP 4 favorite brands in Russia.",
    "schedule section3 event4": "<strong>Kristina Lystina — Development manager, Shiptor.ru</strong> Any owner of an online store will tell you that the finding a reasonably priced delivery service and organizing a delivery is the most difficult part of their job. To inform a customer about the delivery in due time is even more challenging: customer often don't read letters, never check the Spam folder, don't take calls and often out of the network coverage area. What to choose: SMS, voice calls or messengers? We will see into this issue based on several cases and compare the efficiency of each channel.",

    'schedule section4': 'Section 4',
    'schedule section4 pre': 'AWARDING PRIZES',
    'schedule section5': 'Section 5',
    'schedule section5 pre': 'ECOM EХРО`18 EXHIBITION ENDING',


    "map header": "VENUE",
    "map title": "Loft VESNA",
    "map place": "Spartakovskiy lane, 2b1",
    "map descr": "metro Krasnoselskaya (5 min), metro Baumanskaya (7 min)",

    'infopartners header':'INFOPARTNERS',
    'partners header': 'PARTNERS',
    'sponsors header': 'SPONSORS',
    'see record': '> Video <',
    'readmore':'Read more &gt;&gt',
    'speaker to be confirmed': 'The speaker is yet to be confirmed'
  }
};

export default en;